[build]
  base = "./"
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_ENV = "production"
  REACT_APP_API_URL = "https://showmaxx-backend.onrender.com"

[[redirects]]
  from = "/api/*"
  to = "https://showmaxx-backend.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
